import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import ThirdwebProviderRoot from '@/components/general/thirdweb-provider-root'
import Header from '@/components/general/header'
import ConnectWalletPopup from '@/components/general/connect-wallet-popup'
import Modal from '@/components/general/modal'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: {children: React.ReactNode}) {
  return (
    <html lang="en" className=" scroll-smooth">
      <body className={`${inter.className} !mr-0`}>
        <ThirdwebProviderRoot>
          <Header />
          <main className="main max-w-[1080px] m-auto flex flex-col items-center justify-between">
            {/* <section className=" absolute w-full h-full sm:bg-[url('../public/assets/snakes_background.svg')] bg-[length:200px] opacity-1 -z-10" /> */}
            {children}
            <ConnectWalletPopup />
            <Modal></Modal>
          </main>
          
        </ThirdwebProviderRoot>
      </body>
      {/* <div className="fixed top-1/2">OK</div> */}
    </html>
  );
}
